#!/bin/bash

####  Job name
#SBATCH --job-name=GCM-corrk-parallel

####  Request resources here
####  These are typically, number of processors, amount of memory,
####  an the amount of time a job requires.  May include processor
####  type, too.

#SBATCH --nodes=1
#SBATCH --tasks-per-node=4
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4g
##SBATCH --mem=8g
#SBATCH --time=01-00:00:00

#SBATCH --account=erausche0

#### #### ####  These are the least frequently changing options
####  Your e-mail address and when you want e-mail

####SBATCH --mail-user=email@gmail.com
####SBATCH --mail-type=BEGIN,END,FAIL

module load intel/2022.1.2

export OMP_NUM_THREADS=4
export OMP_STACKSIZE=4G
ulimit -s unlimited


./compile_nopg_corrk_par
