#!/bin/bash
#SBATCH --account=pi-larogers
#SBATCH --job-name=MalskyTest
#SBATCH --time=36:00:00
##SBATCH --partition=sandyb
#SBATCH --nodes=1
#SBATCH --exclusive
#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user=isaacmalsky@gmail.com

module load intel/19.1.1
export OMP_NUM_THREADS=1

./compile_nopg
