#!/bin/bash

####  Job name
#SBATCH --job-name=finalhazetest_secondtry

####  Request resources here
####  These are typically, number of processors, amount of memory,
####  an the amount of time a job requires.  May include processor
####  type, too.

#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=50g
#SBATCH --time=14-00:00:00

#SBATCH --account=erausche1

#### #### ####  These are the least frequently changing options
####  Your e-mail address and when you want e-mail

#SBATCH --mail-user=ajwingat@umich.edu
#SBATCH --mail-type=BEGIN,END,FAIL

module load intel/2022.1.2

export OMP_NUM_THREADS=1

./compile_nopg

module load python3.9-anaconda
rm -f fortrantopythonfile.cpython-39-x86_64-linux-gnu.so
python -m numpy.f2py -c fortran_readfort7.f90 -m fortrantopythonfile
python createfort7dictionary.py

python rename_planetrun.py
