      PROGRAM TEST

      INTEGER NLAT,NLON
      PARAMETER(NLAT=10,NLON=20)
      REAL AMU(NLAT,NLON),ALAT(NLAT),ALON(NLON),SSLAT,SSLON,PI2
      PI2=2.*3.14159
      SSLAT=45.
      SSLON=0.

      DO 10 ILAT=1,NLAT
         ALAT(ILAT)=(180./(NLAT-1))*(ILAT-1)-90.
 10   CONTINUE
      DO 20 ILON=1,NLON
         ALON(ILON)=(ILON-1)*(360./(NLON-1))
 20   CONTINUE

C      WRITE(*,*) ALAT
C      WRITE(*,*) ALON

      DO 30 ILAT=1,NLAT
         DO 40 ILON=1,NLON
            AMU(ILAT,ILON)=SIN(ALAT(ILAT)/360.*PI2)*SIN(SSLAT/360.*PI2)
     &           +COS(ALAT(ILAT)/360.*PI2)*COS(SSLAT/360.*PI2)
     &           *COS((ALON(ILON)-SSLON)/360.*PI2)
            WRITE(*,*) ALAT(ILAT),ALON(ILON),AMU(ILAT,ILON)
C            WRITE(*,*) SIN(ALAT(ILAT)/360.*PI2)*SIN(SSLAT/360.*PI2)
C            WRITE(*,*) COS(ALAT(ILAT)/360.*PI2)*COS(SSLAT/360.*PI2)
C            WRITE(*,*) COS((ALON(ILON)-SSLON)/360.*PI2)
 40      CONTINUE
 30   CONTINUE

      WRITE(*,*) SSLAT,SSLON

      STOP
      END
